export const initialState = [
    {
      userId: 1,
      id: 1,
      title: "Buy groceries",
      completed: false,
    },
    {
      userId: 1,
      id: 2,
      title: "Go for a run",
      completed: false,
    },
    {
      userId: 1,
      id: 3,
      title: "Attend meeting with team",
      completed: false,
    },
    {
      userId: 1,
      id: 4,
      title: "Read a book",
      completed: true,
    },
    {
      userId: 1,
      id: 5,
      title: "Write report for project",
      completed: false,
    },
    {
      userId: 1,
      id: 6,
      title: "Call parents",
      completed: false,
    },
    {
      userId: 1,
      id: 7,
      title: "Do laundry",
      completed: false,
    },
    {
      userId: 1,
      id: 8,
      title: "Attend yoga class",
      completed: true,
    },
    {
      userId: 1,
      id: 9,
      title: "Water the plants",
      completed: false,
    },
    {
      userId: 1,
      id: 10,
      title: "Cook dinner",
      completed: true,
    },
    {
      userId: 1,
      id: 11,
      title: "Take out the trash",
      completed: true,
    },
    {
      userId: 1,
      id: 12,
      title: "Practice coding",
      completed: true,
    },
    {
      userId: 1,
      id: 13,
      title: "Pay bills",
      completed: false,
    },
    {
      userId: 1,
      id: 14,
      title: "Watch a movie",
      completed: true,
    },
    {
      userId: 1,
      id: 15,
      title: "Clean the house",
      completed: true,
    },
    {
      userId: 1,
      id: 16,
      title: "Go to the gym",
      completed: true,
    },
    {
      userId: 1,
      id: 17,
      title: "Take a walk",
      completed: true,
    },
    {
      userId: 1,
      id: 18,
      title: "Study for exam",
      completed: false,
    },
    {
      userId: 1,
      id: 19,
      title: "Plan vacation",
      completed: true,
    },
    {
      userId: 1,
      id: 20,
      title: "Organize desk",
      completed: true,
    },
  ];
  